services:
  docker-mysql:
    image: mysql:5.7
    environment:
    - MYSQL_USER = root
    - MYSQL_ROOT_PASSWORD = 1234
    ports:
      - 3307:3306
      
  app:
    depends_on:
      - docker-mysql
    image: 'back-neoris:latest'
    build:
      context: .
    environment:
       - SPRING_DATASOURCE_URL = jdbc:mysql://docker-mysql:3306/test_neoris?useSSL=false
       - SPRING_DATASOURCE_USERNAME = root
       - SPRING_DATASOURCE_PASSWORD = 1234
       - SPRING_JPA_HIBERNATE_DLL_AUTO = udate
       - SPRING_JPA_SHOW_SQL = true
       - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL = true 
    container_name: test-neoris
    ports:
      - 8080:8080

